[tool.poetry]
name = "ray-tracing"
version = "0.1.0"
description = ""
authors = ["vitor-amartins <vmam@cin.ufpe.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.25.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
